--- 
language: node_js
node_js: 
  - node
sudo: true

git: 
  quiet: true

install: 
  - "eval \"$(curl -fsSL https://gist.githubusercontent.com/sambacha/ece2fe5a48995e598560402e0f907e17/raw/b961edbb66d16a0f5e03310a37cf989433839b3c/travisci-node-npm-install.bash\""